"""initial schema with entry and admission_number

Revision ID: ad77723bc739
Revises: 
Create Date: 2026-06-19 08:12:51.698973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad77723bc739'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('entry', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry')
    )
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.create_index('idx_school_name', ['name'], unique=False)
        batch_op.create_index('idx_school_type', ['type'], unique=False)

    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'grade', name='uq_subject_name_grade')
    )
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_index('idx_subject_grade', ['grade'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_number', name='uq_student_admission_number')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('idx_student_grade', ['grade'], unique=False)
        batch_op.create_index('idx_student_school_grade', ['school_id', 'grade'], unique=False)
        batch_op.create_index('idx_student_school_id', ['school_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('term', sa.String(length=10), nullable=False),
    sa.Column('exam', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cbc_level', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.create_index('idx_mark_approved_by', ['approved_by'], unique=False)
        batch_op.create_index('idx_mark_status', ['status'], unique=False)
        batch_op.create_index('idx_mark_student_id', ['student_id'], unique=False)
        batch_op.create_index('idx_mark_student_term_year', ['student_id', 'term', 'year'], unique=False)
        batch_op.create_index('idx_mark_subject_id', ['subject_id'], unique=False)
        batch_op.create_index('idx_mark_submitted_by', ['submitted_by'], unique=False)
        batch_op.create_index('idx_mark_term_year_exam', ['term', 'year', 'exam'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.drop_index('idx_mark_term_year_exam')
        batch_op.drop_index('idx_mark_submitted_by')
        batch_op.drop_index('idx_mark_subject_id')
        batch_op.drop_index('idx_mark_student_term_year')
        batch_op.drop_index('idx_mark_student_id')
        batch_op.drop_index('idx_mark_status')
        batch_op.drop_index('idx_mark_approved_by')

    op.drop_table('mark')
    op.drop_table('user')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('idx_student_school_id')
        batch_op.drop_index('idx_student_school_grade')
        batch_op.drop_index('idx_student_grade')

    op.drop_table('student')
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_index('idx_subject_grade')

    op.drop_table('subject')
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_index('idx_school_type')
        batch_op.drop_index('idx_school_name')

    op.drop_table('school')
    # ### end Alembic commands ###
